spring.autoconfigure.exclude[0]=org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration
spring.autoconfigure.exclude[1]=org.springframework.boot.jdbc.autoconfigure.DataSourceTransactionManagerAutoConfiguration
spring.autoconfigure.exclude[2]=org.springframework.boot.hibernate.autoconfigure.HibernateJpaAutoConfiguration
spring.autoconfigure.exclude[3]=org.springframework.boot.security.autoconfigure.SecurityAutoConfiguration
spring.autoconfigure.exclude[4]=org.springframework.boot.security.autoconfigure.UserDetailsServiceAutoConfiguration
spring.autoconfigure.exclude[5]=org.springframework.boot.security.autoconfigure.web.servlet.ServletWebSecurityAutoConfiguration
server.port=8081
